# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))
import os
import sys
import glob
# sys.path.insert(0, os.path.abspath('.'))
to_add = list(set([os.path.dirname(i) for i
                   in glob.glob('../../**', recursive=True)]))
to_add = [os.path.abspath(i) for i in to_add if '__pycache__' not in i]
for i in range(len(to_add)):
    sys.path.insert(0, to_add[i])

# -- Project information -----------------------------------------------------

project = 'GFAST Landing Page'
copyright = '2018, GFAST'
author = 'GFAST'

# The short X.Y version
version = ''
# The full version, including alpha/beta/rc tags
release = '0.0.1'


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    #'easydev.copybutton',
    'sphinx.ext.autodoc',
	'sphinx.ext.autosummary',
    'sphinx.ext.intersphinx',
    #'sphinxcontrib.httpdomain',
    #'sphinxcontrib.autohttp.flask',
    #'sphinxcontrib.autohttp.flaskqref',	
    'sphinx.ext.ifconfig'
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'GFASTLandingPagedoc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'GFASTLandingPage.tex', 'GFAST Landing Page Documentation',
     'GFAST', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'gfastlandingpage', 'GFAST Landing Page Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'GFASTLandingPage', 'GFAST Landing Page Documentation',
     author, 'GFASTLandingPage', 'One line description of project.',
     'Miscellaneous'),
]


# -- Extension configuration -------------------------------------------------

# -- Options for intersphinx extension ---------------------------------------

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {'lanspector': ('../../../LANspector/doc/build', (None, '../../../LANspector/doc/build/objects.inv')),
					   'mstools': ('../../../MS_tools/doc/build', (None, '../../../MS_tools/doc/build/objects.inv')),
					   'ggytools': ('../../../GGY_tools/doc/build', (None, '../../../GGY_tools/doc/build/objects.inv')),
					   'chi': ('../../../ComputeHourInvestigator/doc/build', (None, '../../../ComputeHourInvestigator/doc/build/objects.inv')),
					   'csi': ('../../../ComputeStorageInvestigator/doc/build', (None, '../../../ComputeStorageInvestigator/doc/build/objects.inv')),
					   'abglrs': ('../../../ABGLRS/doc/build', (None, '../../../ABGLRS/doc/build/objects.inv')),    
					   'model_invent': ('../../../Model-Inventory/doc/build', (None, '../../../Model-Inventory/doc/build/objects.inv')),
					   'gfastdocs': ('../../../gfastdocs/doc/build', (None, '../../../gfastdocs/doc/build/objects.inv')),
					   'admailout': ('../../../ActiveDirectoryWorkday_mailout/doc/build', (None, '../../../ActiveDirectoryWorkday_mailout/doc/build/objects.inv')),
					   'gfastcentral': ('../../../GFASTCentral/doc/build', (None, '../../../GFASTCentral/doc/build/objects.inv')),    
		}
	
intersphinx_cache_limit = 0	
	
	
	
	